# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12ba8d8d1a9184590353566101e78fdfe29f533b440c01d4be6bff5d483d32c2c6af785234d161b24c2307bbd74885b0cd1f508cfa92a249a104740cc9d4f67

test:
  secret_key_base: 46bcf2af8feba83dec1facb94ad19a3b458ce6804ff6daeadbe42ed7a710f3247a346b462b7192a56d09ab1cc32ad4275cc96be00c272acb39388316f63b924f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
